heat_template_version: pike

description: >
  OpenStack Glance service configured with Puppet

parameters:
  DockerGlanceApiImage:
    description: image
    type: string
  DockerGlanceApiConfigImage:
    description: The container image to use for the glance_api config_volume
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EnableInternalTLS:
    type: boolean
    default: false
  GlanceNfsEnabled:
    default: false
    description: >
      When using GlanceBackend 'file', mount NFS share for image storage.
    type: boolean

conditions:

  internal_tls_enabled: {equals: [{get_param: EnableInternalTLS}, true]}
  nfs_backend_enabled: {equals: [{get_param: GlanceNfsEnabled}, true]}


resources:

  ContainersCommon:
    type: ./containers-common.yaml

  MySQLClient:
    type: ../../puppet/services/database/mysql-client.yaml

  GlanceApiPuppetBase:
    type: ../../puppet/services/glance-api.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceData: {get_param: ServiceData}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}

outputs:
  role_data:
    description: Role data for the Glance API role.
    value:
      service_name: {get_attr: [GlanceApiPuppetBase, role_data, service_name]}
      config_settings:
        map_merge:
          - get_attr: [GlanceApiPuppetBase, role_data, config_settings]
          - glance::api::sync_db: false
      step_config: &step_config
        list_join:
          - "\n"
          - - {get_attr: [GlanceApiPuppetBase, role_data, step_config]}
            - {get_attr: [MySQLClient, role_data, step_config]}
      service_config_settings: {get_attr: [GlanceApiPuppetBase, role_data, service_config_settings]}
      # BEGIN DOCKER SETTINGS #
      puppet_config:
        config_volume: glance_api
        puppet_tags: glance_api_config,glance_api_paste_ini,glance_swift_config,glance_cache_config
        step_config: *step_config
        config_image: {get_param: DockerGlanceApiConfigImage}
      apbs_config:
        glance:
          # NOTE(flaper87): We should really find a better way to login to k8s/openshift
          coe_host: "https://38.145.33.131:8443/"
          config_files: "/opt/apb/.kube/config"
          kube_context: "openstack/38-145-33-131:8443/developer"
          hiera_data_file: '/etc/puppet/hieradata/service_configs.json'
      docker_config:
        # Kolla_bootstrap/db_sync runs before permissions set by kolla_config
        step_3:
          glance:
            image: "tripleoupstream/tripleo-k8s-glance:latest"
            net: host
            privileged: false
            user: root
            command:
              - provision
              - -e
              - "@/var/lib/tripleo-config/apbs/keystone.yml"
            volumes: &glance_volumes
              list_concat:
                - {get_attr: [ContainersCommon, volumes]}
                -
                  - /var/lib/kolla/config_files/glance_api.json:/var/lib/kolla/config_files/config.json
                  - /var/lib/config-data/puppet-generated/glance_api/:/var/lib/kolla/config_files/src:ro
                  - /var/log/containers/glance:/var/log/glance
                  - /var/log/containers/httpd/glance-api:/var/log/httpd
                  - /etc/ceph:/var/lib/kolla/config_files/src-ceph:ro
                  -
                    if:
                      - nfs_backend_enabled
                      - /var/lib/glance:/var/lib/glance
                      - ''
            environment:
              - OPENSHIFT_TARGET=https://38.145.33.131:8443
              - OPENSHIFT_USER=developer
              - OPENSHIFT_PASS=developer
      host_prep_tasks:
        - name: create persistent logs directory
          file:
            path: "{{ item }}"
            state: directory
          with_items:
            - /var/log/containers/glance
            - /var/log/containers/httpd/glance-api
        - name: ensure ceph configurations exist
          file:
            path: /etc/ceph
            state: directory
      upgrade_tasks:
        - name: Stop and disable glance_api service
          tags: step2
          service: name=openstack-glance-api state=stopped enabled=no
      metadata_settings:
        get_attr: [GlanceApiPuppetBase, role_data, metadata_settings]
